title: "Kaia Layn"
description: "Digital AI Creator"
theme: minima

collections:
  lists:
    output: true
    permalink: /lists/:name/

defaults:
  - scope:
      path: ""
      type: "lists"
    values:
      layout: "list"
